package com.colisa.canyonbunny.util;


public class Constants {
    // Visible game word is 5 meters wide and 5 meters tall
    public static final float VIEWPORT_WIDTH = 5;
    public static final float VIEWPORT_HEIGHT = 5;

    // Location of description file for texture atlas
    public static final String TEXTURE_ATLAS_OBJECTS = "images/canyonbunny.pack.atlas";

    // Assets constants
    public static final String BUNNY_HEAD = "bunny_head";
    public static final String ROCK_EDGE = "rock_edge";
    public static final String ROCK_MIDDLE = "rock_middle";
    public static final String GOLD_COIN = "item_gold_coin";
    public static final String FEATHER = "item_feather";

    public static final String CLOUDS_1 = "cloud01";
    public static final String CLOUDS_2 = "cloud02";
    public static final String CLOUDS_3 = "cloud03";
    public static final String MOUNTAIN_LEFT = "mountain_left";
    public static final String MOUNTAIN_RIGHT = "mountain_right";
    public static final String WATER_OVERLAY = "water_overlay";

    public static final String LEVEL_1 = "levels/level-01.png";
    public static final float TIME_DELAY_GAME_OVER = 3;

    public static final float VIEWPORT_GUI_WIDTH = 800.0f;
    public static final float VIEWPORT_GUI_HEIGHT = 480.0f;

    public static final int LIVES_START = 3;
    // Fonts
    public static final String FONTS = "fonts/arial-15.fnt";
    // Power Up
    public static final float ITEM_FEATHER_POWERUP_DURATION = 9.0f;
    // BunnyHead
    public static final float JUMP_TIME_MAX = 0.3f;
    public static final float JUMP_TIME_MIN = 0.1f;
    public static final float JUMP_TIME_OFFSET_FLYING = JUMP_TIME_MAX - 0.018f;
    /*
        There are two categories for the following constants.
        images - There are generated by texture packer the directory is deleted in eash rebuild
        images-user - These are ones generated manually by user. eg downloaded from internet
    */
    public static final String TEXTURE_ATLAS_UI = "images/canyonbunny-ui.pack.atlas";
    public static final String TEXTURE_ATLAS_LIBGDX_UI = "images-user/uiskin.atlas";
    public static final String SKIN_CANYONBUNNY_UI = "images-user/canyonbunny-iu.json";
    public static final String SKIN_LIBGDX_UI = "images-user/uiskin.json";
    // Game preferences file
    public static final String PREFERENCES = "canyonbunny.prefs";
    // Camera constants
    static final float MAX_ZOOM_IN = 0.25f;
    static final float MAX_ZOOM_OUT = 10f;
}
