package com.colisa.canyonbunny.util;


public class Constants {
    // Visible game word is 5 meters wide and 5 meters tall
    public static final float VIEWPORT_WIDTH = 5;
    public static final float VIEWPORT_HEIGHT = 5;

    // Location of description file for texture atlas
    public static final String TEXTURE_ATLAS_OBJECTS = "images/canyonbunny.pack.atlas";

    // Assets constants
    public static final String BUNNY_HEAD = "bunny_head";
    public static final String ROCK_EDGE = "rock_edge";
    public static final String ROCK_MIDDLE = "rock_middle";
    public static final String GOLD_COIN = "item_gold_coin";
    public static final String FEATHER = "item_feather";

    public static final String CLOUDS_1 = "cloud01";
    public static final String CLOUDS_2 = "cloud02";
    public static final String CLOUDS_3 = "cloud03";
    public static final String MOUNTAIN_LEFT = "mountain_left";
    public static final String MOUNTAIN_RIGHT = "mountain_right";
    public static final String WATER_OVERLAY = "water_overlay";

    public static final String LEVEL_1 = "levels/level-01.png";
    public static final float TIME_DELAY_GAME_OVER = 3;

    public static final float VIEWPORT_GUI_WIDTH = 800.0f;
    public static final float VIEWPORT_GUI_HEIGHT = 480.0f;

    public static final int LIVES_START = 3;
    // Fonts
    public static final String FONTS = "fonts/arial-15.fnt";
    // Power Up
    public static final float ITEM_FEATHER_POWERUP_DURATION = 9.0f;
    // BunnyHead
    public static final float JUMP_TIME_MAX = 0.3f;
    public static final float JUMP_TIME_MIN = 0.1f;
    public static final float JUMP_TIME_OFFSET_FLYING = JUMP_TIME_MAX - 0.018f;
    // Particles
    public static final String DUST_PARTICLES = "particles/dust.pfx";
    /*
        There are two categories for the following constants.
        images - There are generated by texture packer the directory is deleted in eash rebuild
        images-user - These are ones generated manually by user. eg downloaded from internet
    */
    public static final String TEXTURE_ATLAS_UI = "images/canyonbunny-ui.pack.atlas";
    public static final String TEXTURE_ATLAS_LIBGDX_UI = "images-user/uiskin.atlas";
    public static final String SKIN_CANYONBUNNY_UI = "images-user/canyonbunny-iu.json";
    public static final String SKIN_LIBGDX_UI = "images-user/uiskin.json";
    // Game preferences file
    public static final String PREFERENCES = "canyonbunny.prefs";
    // Camera Helper
    public static final float FOLLOW_SPEED = 4.0f;
    // Rocks
    public static final float FLOAT_CIRCLE_TIME = 2.0F;
    public static final float FLOAT_AMPLITUDE = 0.25f;
    // Sounds
    public static final String JUMP = "sounds/jump.wav";
    public static final String JUMP_WITH_FEATHER = "sounds/jump_with_feather.wav";
    public static final String PICKUP_COIN = "sounds/pickup_coin.wav";
    public static final String PICKUP_FEATHER = "sounds/pickup_feather.wav";
    public static final String LIVE_LOST = "sounds/live_lost.wav";
    // Music
    public static final String MUSIC_O1 = "music/keith303_-_brand_new_highscore.mp3";
    // Camera constants
    static final float MAX_ZOOM_IN = 0.25f;
    static final float MAX_ZOOM_OUT = 10f;

}
